# Generated by Django 3.1.5 on 2021-01-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
